trydiffoscope/api/urls.py
from django.conf.urls import url

from . import views

app_name = 'api'

urlpatterns = (
    url(r'^api/v3/comparison$', views.compare, name='compare'),
    url(
        r'^api/v3/comparison/(?P<slug>\w{12})$',
        views.comparison,
        name='comparison',
    ),
)

trydiffoscope/compare/urls.py
from django.conf.urls import url

from . import views

app_name = 'compare'

urlpatterns = (
    url(r'^$', views.view, name='view'),
    url(r'^(?P<slug>\w{12})$', views.poll, name='poll'),
    url(
        r'^(?P<slug>\w{12})\.(?P<extension>html|txt)$',
        views.output,
        name='output',
    ),
)

trydiffoscope/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.views.static import serve

urlpatterns = (
    url(r'', include('trydiffoscope.api.urls', namespace='api')),
    url(r'', include('trydiffoscope.compare.urls', namespace='compare')),
    url(r'', include('trydiffoscope.static.urls', namespace='static')),
)

if settings.DEBUG:
    urlpatterns += (
        url(
            r'^storage/(?P<path>.*)$',
            serve,
            {'document_root': settings.MEDIA_ROOT},
        ),
    )

trydiffoscope/compare/models.py
import os
import datetime
import functools

from django.db import models
from django.shortcuts import resolve_url
from django.utils.crypto import get_random_string

from .enums import StateEnum


def upload_to(instance, filename, prefix=''):
    return os.path.join(instance.slug, prefix, filename)


class Comparison(models.Model):
    file_a = models.FileField(
        upload_to=functools.partial(upload_to, prefix='a')
    )

    file_b = models.FileField(
        upload_to=functools.partial(upload_to, prefix='b')
    )

    state = models.IntegerField(
        choices=[(x.name, x.value) for x in StateEnum],
        default=StateEnum.queued.value,
    )

    output = models.TextField()

    slug = models.CharField(
        unique=True,
        max_length=12,
        default=functools.partial(
            get_random_string, 12, 'abcdefghkpqrstuvxyz'
        ),
    )

    created = models.DateTimeField(default=datetime.datetime.utcnow)
    updated = models.DateTimeField(default=datetime.datetime.utcnow)

    class Meta:
        ordering = ('-created',)
        get_latest_by = 'created'

    def __unicode__(self):
        return u"slug=%s state=%s a=%s b=%s" % (
            self.slug,
            self.state,
            self.file_a.name,
            self.file_b.name,
        )

    def get_state_enum(self):
        return {x.value: x for x in StateEnum}[self.state]

    def get_absolute_url(self):
        return resolve_url('compare:poll', self.slug)

trydiffoscope/compare/forms.py
from django import forms
from django.db import transaction

from .tasks import execute_diffoscope
from .models import Comparison


class CompareForm(forms.ModelForm):
    class Meta:
        model = Comparison
        fields = ('file_a', 'file_b')

    def save(self):
        instance = super(CompareForm, self).save()

        transaction.on_commit(lambda: execute_diffoscope.delay(instance.slug))

        return instance

trydiffoscope/api/views.py
from django.shortcuts import get_object_or_404
from django.views.decorators.http import require_POST

from trydiffoscope.compare.forms import CompareForm
from trydiffoscope.utils.shortcuts import resolve_absolute_uri

from trydiffoscope.compare.models import Comparison

from .decorators import api_method


@api_method()
@require_POST
def compare(request):
    form = CompareForm(request.POST, request.FILES)

    if not form.is_valid():
        return 400, {'errors': form.errors}

    instance = form.save()

    return (
        201,
        {
            'uri': resolve_absolute_uri(
                request, 'api:comparison', instance.slug
            )
        },
    )


@api_method()
def comparison(request, slug):
    instance = get_object_or_404(Comparison, slug=slug)

    response = {
        'uri': resolve_absolute_uri(request, instance),
        'state': instance.get_state_enum().name,
        'formats': {
            x: resolve_absolute_uri(
                request, 'compare:output', instance.slug, y
            )
            for x, y in (('text', 'txt'), ('html', 'html'))
        },
        'created': instance.created,
        'updated': instance.updated,
    }

    return 200, response

trydiffoscope/compare/views.py
from django.conf import settings
from django.shortcuts import render, redirect, get_object_or_404
from django.views.static import serve
from django.core.files.storage import default_storage
from django.views.decorators.cache import never_cache

from .forms import CompareForm
from .enums import StateEnum
from .models import Comparison
from .progress import get_progress


def view(request):
    if request.method == 'POST':
        form = CompareForm(request.POST, request.FILES)

        if form.is_valid():
            instance = form.save()

            return redirect(instance)
    else:
        form = CompareForm()

    return render(request, 'compare/view.html', {'form': form})


@never_cache
def poll(request, slug):
    comparison = get_object_or_404(Comparison, slug=slug)

    state = comparison.get_state_enum()

    if state == StateEnum.different:
        return redirect('compare:output', comparison.slug, 'html')

    try:
        current, total = get_progress(comparison)
        progress = int(100 * current / total)
    except Exception:
        progress = 0

    queue_position = (
        Comparison.objects.filter(
            state=StateEnum.queued, created__lt=comparison.created
        ).count()
        + 1
    )

    return render(
        request,
        'compare/states/%s.html' % state.name,
        {
            'progress': progress,
            'comparison': comparison,
            'queue_position': queue_position,
        },
    )


def output(request, slug, extension):
    assert settings.DEBUG, "Overridden by nginx configuration"

    return serve(
        request,
        'output.%s' % extension,
        document_root=default_storage.path(slug),
    )

templates/base/base.html
{% extends "base/generic_base.html" %}

{% block body %}

{% if messages %}
{% for message in messages %}
<div class="container alert alert-{% if message.tags == "error" %}danger {% else %}{{ message.tags }}{% endif %}">
  <button type="button" class="close" data-dismiss="alert">×</button>
  {{ message }}
</div>
{% endfor %}
{% endif %}

{% block container %}
<div class="container">
  {% block content %}{% endblock %}
</div>
{% endblock %}

<footer>
  <div class="container">
    <hr>
    <p class="text-muted text-center">
      Copyright &copy; 2015&mdash;{% now "Y" %}
      <a href="https://chris-lamb.co.uk">Chris Lamb</a>.
      Released under the terms of the
      <a href="https://www.gnu.org/licenses/agpl-3.0.en.html">GNU Affero General Public License</a>
      (<a href="https://salsa.debian.org/reproducible-builds/try.diffoscope.org">source</a>).
      <br>
      Results are purged after {{ settings.TRYDIFFOSCOPE_RESULTS_RETENTION_DAYS }}
      day{{ settings.TRYDIFFOSCOPE_RESULTS_RETENTION_DAYS|pluralize }}.
      <a href="{% url "static:privacy" %}">Privacy policy</a>.
      <a href="{% url "static:terms" %}">Terms of service</a>.
    </p>
  </div>
</footer>

{% endblock %}

templates/base/generic_base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="referrer" content="same-origin" />

  <title>{% block title %}trydiffoscope: in-depth comparison of files, archives, and directories{% endblock %}</title>

  {% block css %}
  <link href="{% static "css/bootstrap.css" %}" rel="stylesheet" />
  <link href="{% static "css/trydiffoscope.css" %}" rel="stylesheet" media="screen" />
  {% endblock %}

  {% block extrahead %}{% endblock %}
</head>
<body class="{% block body_classes %}{% endblock %}">
  {% block body %}{% endblock %}
</body>
</html>

templates/compare/include_footer.html
<div class="footer">
  <p style="float: left;">
    <a href="{% url "compare:output" comparison.slug "txt" %}">View text version</a>.
    Results are kept for {{ settings.TRYDIFFOSCOPE_RESULTS_RETENTION_DAYS }} day{{ settings.TRYDIFFOSCOPE_RESULTS_RETENTION_DAYS|pluralize }}.
  </p>
  <p style="float: right; text-align: right; line-height: 24px;">
    Hosting provided by<br>
    <a href="https://www.iomart.com/"><img src="{% static "images/iomart.png" %}" alt="iomart"></a>
  </p>
</div>

templates/compare/states/error.html
{% extends "base/base.html" %}

{% block content %}

<div class="page-header">
  <h1>
    Whoops!
    <small>An error occurred when comparing your files</small>
  </h1>
</div>

<pre>{{ comparison.output }}</pre>

{% endblock%}

templates/compare/states/identical.html
{% extends "base/base.html" %}

{% block body_classes %}{{ block.super }} f_center{% endblock %}

{% block content %}
  <div class="row">
    <p class="text-center lead">
      Your files are identical!
    </p>
  </div>
{% endblock%}

templates/compare/states/queued.html
{% extends "base/base.html" %}

{% block body_classes %}{{ block.super }} f_compare_queued f_center{% endblock %}

{% block title %}Please wait&hellip;{% endblock %}

{% block extrahead %}
{{ block.super }}
<meta http-equiv="refresh" content="2">
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-sm-4 col-sm-offset-4">
      <p class="text-center lead">
        {% if comparison.get_state_enum.name == "queued" %}
          In position #{{ queue_position }} in queue, please wait&hellip;
        {% else %}
          Comparing your files, please wait&hellip;
        {% endif %}
      </p>

      <div class="progress">
        <div class="progress-bar progress-bar-striped" style="width: {{ progress }}%;">{{ progress }}%</div>
      </div>

    </div>
  </div>

{% endblock%}

templates/compare/states/running.html
queued.html

templates/compare/states/timeout.html
{% extends "base/base.html" %}

{% block content %}

<div class="page-header">
  <h1>
    Timeout
    <small>Sorry, it took too long to process your files.</small>
  </h1>
  <p>Install and run <a href="https://diffoscope.org/">diffoscope</a> on your system to avoid this limit.</p>
</div>

{% endblock%}

templates/compare/view.html
{% extends "base/base.html" %}

{% block body_classes %}{{ block.super }} f_compare_view{% endblock %}

{% block container %}

<a class="hidden-xs" href="https://salsa.debian.org/reproducible-builds/try.diffoscope.org"><img style="position: absolute; top: 0; left: 0; border: 0;" src="{% static "images/salsa.png" %}" alt="Fork me on Salsa"></a>

<div class="wrapper">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-4 logo">
        <a href="{% url "compare:view" %}">
          <img src="{% static "images/diffoscope.png" %}" class="img-responsive center-block">
        </a>
      </div>

      <div class="col-xs-12 col-sm-8">
        <h1>
          Try diffoscope now&hellip;
        </h1>

        <p class="lead">
          <a href="https://diffoscope.org/">diffoscope</a> is a tool to get to
          the bottom of what makes files or directories different. It
          recursively unpacks archives of many kinds and transforms various
          binary formats into more human readable forms to compare them.
        </p>

        {% if form.non_field_errors %}
        <div class="has-error">
          {% for x in form.non_field_errors %}
          <p class="help-block">{{ x }}</p>
          {% endfor %}
        </div>
        {% endif %}

        <form
          method="POST"
          class="form-horizontal"
          action=""
          {% if form.is_multipart %}enctype="multipart/form-data"{% endif %}
        >
          {% csrf_token %}

          <div class="row">
            <div class="col-xs-10 col-xs-offset-1">
              <div class="row">
                <div class="col-md-5 col-xs-12">
                  <div class="form-group {% if form.errors.file_a %}has-error{% endif %}">
                    <label for="{{ form.file_a.id_for_label }}">
                      File #1
                      <span class="text-muted">(max: {% widthratio settings.TRYDIFFOSCOPE_MAX_UPLOAD_SIZE_MEGABYTES 2 1 %}MB)</span>
                    </label>
                    <input
                      id="{{ form.file_a.id_for_label }}"
                      type="file"
                      class="form-control input-lg"
                      name="{{ form.file_a.html_name }}"
                      value="{{ form.file_a.value|default:"" }}"
                      maxlength="{{ form.fields.file_a.max_length }}"
                      {% if form.fields.file_a.required %}required{% endif %}
                    >
                    {% for x in form.errors.file_a %}
                      <p class="help-block">{{ x }}</p>
                    {% endfor %}
                  </div>
                </div>
                <div class="col-md-5 col-md-offset-1 col-xs-12 col-xs-offset-0">
                  <div class="form-group {% if form.errors.file_b %}has-error{% endif %}">
                    <label for="{{ form.file_b.id_for_label }}">
                      File #2
                      <span class="text-muted">(max: {% widthratio settings.TRYDIFFOSCOPE_MAX_UPLOAD_SIZE_MEGABYTES 2 1 %}MB)</span>
                    </label>
                    <input
                      id="{{ form.file_b.id_for_label }}"
                      type="file"
                      class="form-control input-lg"
                      name="{{ form.file_b.html_name }}"
                      value="{{ form.file_b.value|default:"" }}"
                      maxlength="{{ form.fields.file_b.max_length }}"
                      {% if form.fields.file_b.required %}required{% endif %}
                    >
                    {% for x in form.errors.file_b %}
                      <p class="help-block">{{ x }}</p>
                    {% endfor %}
                  </div>
                </div>
              </div>

              <div class="form-group upload">
                <div class="col-sm-9 col-sm-offset-1">
                  <button type="submit" class="btn btn-primary btn-block btn-lg">
                    Upload &amp; compare files
                  </button>
                </div>
              </div>

              <br>

              <p class="lead text-center">
                &hellip; or use the command-line interface:
              </p>

              <div class="card">
                <div class="card-body">
                  <pre class="cli my-0">
$ pip install trydiffoscope <span class="text-muted"> # or: sudo apt install trydiffoscope</span>
$ trydiffoscope --webbrowser /path/to/file1 /path/to/file2</pre>
                </div>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-sm-6">
      <p>
        <em>diffoscope</em> is being developed under the umbrella of the
        <a href="https://reproducible-builds.org/">reproducible-builds.org</a>
        effort, a member project of the
        <a href="https://sfconservancy.org/">Software Freedom Conservancy</a>.
        For contributing, licensing and instructions on how to run
        <em>diffoscope</em> on your own machine, please see
        <a href="https://diffoscope.org/">diffoscope.org</a>.
      </p>
      <p class="text-center">
        <a href="https://reproducible-builds.org/">
          <img src="{% static "images/reproducible-builds.png" %}" class="mx-3 img-responsive center-block"></a>
        <a href="https://sfconservancy.org/">
          <img src="{% static "images/conservancy.png" %}" class="mx-3 img-responsive center-block"></a>
        <a href="https://www.gnu.org/licenses/agpl-3.0.en.html">
          <img src="{% static "images/agplv3.png" %}" class="mx-3 img-responsive center-block"></a>
      </p>
    </div>
    <div class="col-sm-6">
      <br class="visible-xs">
      <p class="text-center text-muted">
        Hosting provided by:
      </p>
      <p class="text-center">
        <a href="https://www.iomart.com">
          <img src="{% static "images/iomart.png" %}" class="img-responsive center-block">
        </a>
      </p>
    </div>
  </div>
</div>
{% endblock%}